#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t tmpfs none /tmp

insmod /blargh.ko
chmod 0600 /flag.txt
chown 0:0 /flag.txt

#setsid /bin/cttyhack setuidgid 0 /bin/sh
setsid /bin/cttyhack setuidgid 1000 /bin/sh

poweroff -f
