#!/bin/sh

chmod 700 -R /root
chown -R ctf:ctf /home/ctf

insmod /root/writeonly.ko
mknod -m 666 /dev/writeonly c `grep writeonly /proc/devices | awk '{print $1;}'` 0

stty -opost
echo 2 > /proc/sys/kernel/kptr_restrict
#echo 0 > /proc/sys/kernel/kptr_restrict # debugging purpose
echo 1 > /proc/sys/kernel/dmesg_restrict

echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"
#cat /proc/kallsyms | grep "T _stext"	# debugging purpose
#cat /proc/kallsyms | grep "t __pfx_write_only_ioctl"	# debugging purpose
#cat /proc/slabinfo | head -n 2 && cat /proc/slabinfo | grep "^kmalloc-1k"

setsid cttyhack setuidgid ctf /bin/sh
#setsid cttyhack setuidgid root /bin/sh

umount /proc
poweroff -d 0 -f
